// config.js
const SUPABASE_URL = 'https://udxltthbwkpyaeyzsuzm.supabase.co'
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkeGx0dGhid2tweWFleXpzdXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE4NjIyMzAsImV4cCI6MjA5NzQzODIzMH0.aUBBQc5pQvGCkNU9JHPonpLJLfmtbdqym11Abt9ovn8'

export { SUPABASE_URL, SUPABASE_ANON_KEY }
